[package]
name = "rust-doom"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4"
num-traits = "0.2"
pixels = "0.13"
winit = "0.28"
winit_input_helper = "0.14"
readonly = "0.2.11"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
